Dramatically speed up repeated builds using ccache

diff --git a/platform/source/medic-core-1.6.1/scripts/build-all b/platform/source/medic-core-1.6.1/scripts/build-all
--- a/platform/source/medic-core-1.6.1/scripts/build-all
+++ b/platform/source/medic-core-1.6.1/scripts/build-all
@@ -65,6 +65,10 @@ main()
     gammu_extra_options='-DWITH_Iconv=OFF'
   fi
 
+  if ! builder_setup_cache; then
+    warn 'Compiler caching could not be enabled'
+  fi
+
   (disable_stack_protector &&
     build_autoconf 'pv' "$stdarg") &&
   \
diff --git a/platform/source/vm-tools-9.4.6/scripts/build-all b/platform/source/vm-tools-9.4.6/scripts/build-all
--- a/platform/source/vm-tools-9.4.6/scripts/build-all
+++ b/platform/source/vm-tools-9.4.6/scripts/build-all
@@ -38,6 +38,10 @@ main()
   [ $? -eq 0 ] \
     || fatal 'Failed to set up build environment'
 
+  if ! builder_setup_cache; then
+    warn 'Compiler caching could not be enabled'
+  fi
+
   build_autoconf 'pv' "$stdarg" &&
   \
   (disable_parallelism && simple_cflags &&
