Rework filesystem mounting code in container-start.

diff --git a/platform/initrd/common/boot/container-start b/platform/initrd/common/boot/container-start
--- a/platform/initrd/common/boot/container-start
+++ b/platform/initrd/common/boot/container-start
@@ -3,28 +3,30 @@
 source '/boot/include/utility'
 source '/boot/include/startup'
 source '/boot/include/package'
-
-mount_filesystems()
-{
-  info 'Mounting filesystems...'
-
-  for fs in /proc /sys /dev/pts /dev/shm; do
-    mount "$fs" \
-      || fatal "Unable to mount the $fs filesystem"
-  done
-
-  return 0
-}
-
-mount_filesystems
 source '/boot/include/supervisor'
 
 main()
 {
+  # Mount all filesystems:
+  #   Do this before initializing the supervisor library,
+  #   because it checks for the presence of /proc at startup.
+
+  info 'Mounting filesystems...'
+
+  mount_special_filesystems proc /proc sysfs /sys \
+    devpts /dev/pts tmpfs /dev/shm cgroup /sys/fs/cgroup
+
+  if [ "$?" -ne 0 ]; then
+    fatal 'Failed to mount one or more required filesystems'
+  fi
+
+  supervisor_init
+
   # Update packages:
   #   Update each package necessary for proper startup; the `package_update`
   #   function will avoid overwriting existing binaries if it's able to.
 
+  log 'Starting software update process'
   info 'Setting up software...'
 
   local total_packages='0'
diff --git a/platform/initrd/common/boot/include/startup b/platform/initrd/common/boot/include/startup
--- a/platform/initrd/common/boot/include/startup
+++ b/platform/initrd/common/boot/include/startup
@@ -21,6 +21,31 @@ is_storage_empty()
   return "$?"
 }
 
+mount_special_filesystems()
+{
+  local rv='0'
+
+  while [ "$#" -gt 0 ]; do
+
+    local type="$1"
+    local dir="$2"
+    shift 2
+
+    local original_type="`stat -fc %T "$dir"`"
+
+    if [ "$original_type" != "$type" ]; then
+      if ! mount -t "$type" "$type" "$dir"; then
+        warn "Failed to mount a '$type' filesystem at '$dir'"
+        rv="$(($rv + 1))"
+      fi
+    else
+      log "Volume of type '$type' is already mounted at '$dir'"
+    fi
+  done
+
+  return "$?"
+}
+
 disconnect_storage()
 {
   local device="$1"
diff --git a/platform/initrd/common/boot/include/supervisor b/platform/initrd/common/boot/include/supervisor
--- a/platform/initrd/common/boot/include/supervisor
+++ b/platform/initrd/common/boot/include/supervisor
@@ -18,15 +18,11 @@ _perform_startup_checks()
   done
 
   if [ "$rv" -ne 0 ]; then
-    warn 'Mount all required filesystems and try again'
+    warn 'At least one required filesystem is not mounted'
   fi
 
   return "$rv"
 }
-
-if ! _perform_startup_checks; then
-  fatal 'Startup checks failed for supervisor library'
-fi
 
 _safe_waitpid()
 {
@@ -560,6 +556,15 @@ _supervisor_accounting_write()
   esac
 
   return "$?"
+}
+
+supervisor_init()
+{
+  if ! _perform_startup_checks; then
+    fatal 'Startup checks failed for supervisor library'
+  fi
+
+  return 0
 }
 
 supervisor_accounting_read()
