Add error message when package-install called on missing file
Closes #19

diff --git a/platform/initrd/common/boot/package-install b/platform/initrd/common/boot/package-install
--- a/platform/initrd/common/boot/package-install
+++ b/platform/initrd/common/boot/package-install
@@ -23,6 +23,8 @@ main()
   fi
 
   for path in "$@"; do
+    [ -f "$path" ] || fatal "File not found: $path"
+
     local package="`package_extract_name "$path"`" \
       || fatal "Failed to determine name of package '$path'"
 
