Improvements to package and supervision scripts.
Make `package-install` and `package-remove` work properly; don't freak out
during installation/removal/supervision if a package has no services; rework
default logging code to work well for interactive use; provide completion
messages for start/stop/install/remove operations to make success obvious.

This also adds an `info` logging target for the default logging implementation;
I'll rework the non-interactive logging code in `include/logger` to support this
in the next commit.

diff --git a/platform/initrd/common/boot/package-install b/platform/initrd/common/boot/package-install
--- a/platform/initrd/common/boot/package-install
+++ b/platform/initrd/common/boot/package-install
@@ -2,6 +2,7 @@
 
 source '/boot/include/utility'
 source '/boot/include/package'
+source '/boot/include/supervisor'
 
 main()
 {
@@ -12,7 +13,6 @@ main()
   require_root
 
   for path in "$@"; do
-
     local package="`package_extract_name "$path"`" \
       || fatal "Failed to determine name of package '$path'"
 
@@ -22,11 +22,19 @@ main()
     package_setup "$package" \
       || fatal "Failed to run setup script for package '$path'"
 
-    supervisor_start "$package" \
-      || fatal "Failed to start supervisor for package '$package'"
+    supervisor_start "$package"
+    local rv="$?"
 
+    if [ "$rv" -eq 254 ]; then
+      warn "Package '$package' has no services to start; continuing"
+    elif [ "$rv" -ne 0 ]; then
+      fatal "Failed to start supervisor for package '$package'"
+    fi
+
+    info "Package '$package' successfully installed"
   done
 
+  info 'All specified packages were successfully installed'
   return 0
 }
 
