Toward medic/medic-os#39.
Ensure that the requested package exists in `supervisor_list_all_services`.
Improve subshells/loop error handling in the `svc-*` family of scripts.

diff --git a/platform/initrd/common/boot/supervisor-enable b/platform/initrd/common/boot/supervisor-enable
--- a/platform/initrd/common/boot/supervisor-enable
+++ b/platform/initrd/common/boot/supervisor-enable
@@ -9,6 +9,14 @@ enable()
   local service="$2"
   local is_wildcard="$3"
 
+  # Sanity check:
+  #   Make sure the service we're trying to enable actually exists.
+
+  if ! supervisor_service_exists "$package" "$service"; then
+    warn "Service '$package/$service' doesn't exist"
+    return 1
+  fi
+
   if [ "$is_wildcard" ]; then
     if supervisor_is_service_enabled "$package" "$service"; then
       warn "Service '$package/$service is already enabled; skipping"
@@ -35,24 +43,26 @@ main()
   require_root
   supervisor_init
 
+  local rv=''
+
   if [ "$#" -le 0 ]; then
     supervisor_list_all_services "$package" | while read service; do
       enable "$package" "$service" 't'
+      local r="$?"; [ "$r" -eq 0 ] || exit "$r"
     done
-    local rv="$?"
-    [ "$rv" -ne 0 ] && return "$rv"
+    rv="$?"
   else
     for service in "$@"; do
       enable "$package" "$service"
+      rv="$?"
     done
   fi
 
-  if [ $# -le 0 ]; then
-    success "Finished enabling services in package '$package'"
-  else
-    success "Selected services in package '$package' are now enabled"
+  if [ "$rv" -ne 0 ]; then
+    fatal "Failed to enable one or more services in package '$package'"
   fi
 
+  success "Finished enabling services in package '$package'"
   return 0
 }
 
diff --git a/platform/initrd/common/boot/svc-down b/platform/initrd/common/boot/svc-down
--- a/platform/initrd/common/boot/svc-down
+++ b/platform/initrd/common/boot/svc-down
@@ -9,6 +9,14 @@ down()
   local service="$2"
   local is_wildcard="$3"
 
+  # Sanity check:
+  #   Make sure the service we're trying to stop actually exists.
+
+  if ! supervisor_service_exists "$package" "$service"; then
+    warn "Service '$package/$service' doesn't exist"
+    return 1
+  fi
+
   if [ "$is_wildcard" ]; then
     if supervisor_is_service_disabled "$package" "$service"; then
       warn "Service '$package/$service' is disabled; skipping"
@@ -38,24 +46,26 @@ main()
   require_root
   supervisor_init
 
+  local rv=''
+
   if [ "$#" -le 0 ]; then
     supervisor_list_all_services "$package" | while read service; do
       down "$package" "$service" 't'
+      local r="$?"; [ "$r" -eq 0 ] || exit "$r"
     done
     rv="$?"
-    [ "$rv" -ne 0 ] && return "$rv"
   else
     for service in "$@"; do
       down "$package" "$service"
+      rv="$?"
     done
   fi
 
-  if [ $# -le 0 ]; then
-    success "Finished stopping services in package '$package'"
-  else
-    success "Selected services in package '$package' have stopped"
+  if [ "$rv" -ne 0 ]; then
+    fatal "Failed to stop one or more services in package '$package'"
   fi
 
+  success "Finished stopping services in package '$package'"
   return 0
 }
 
diff --git a/platform/initrd/common/boot/svc-reload b/platform/initrd/common/boot/svc-reload
--- a/platform/initrd/common/boot/svc-reload
+++ b/platform/initrd/common/boot/svc-reload
@@ -8,6 +8,14 @@ reload()
   local package="$1"
   local service="$2"
 
+  # Sanity check:
+  #   Make sure the service we're trying to reload actually exists.
+
+  if ! supervisor_service_exists "$package" "$service"; then
+    warn "Service '$package/$service' doesn't exist"
+    return 1
+  fi
+
   supervisor_service_reload "$package" "$service" \
     || fatal "Failed to reload configuration for '$package/$service'"
 
@@ -28,24 +36,26 @@ main()
   require_root
   supervisor_init
 
+  local rv=''
+
   if [ "$#" -le 0 ]; then
     supervisor_list_expected_services "$package" | while read service; do
       reload "$package" "$service"
+      local r="$?"; [ "$r" -eq 0 ] || exit "$r"
     done
-    local rv="$?"
-    [ "$rv" -ne 0 ] && return "$rv"
+    rv="$?"
   else
     for service in "$@"; do
       reload "$package" "$service"
+      rv="$?"
     done
   fi
  
-  if [ $# -le 0 ]; then
-    success "All services in package '$package' have reloaded"
-  else
-    success "Selected services in package '$package' have reloaded"
+  if [ "$rv" -ne 0 ]; then
+    fatal "Failed to reload one or more services in package '$package'"
   fi
 
+  success "Finished reloading services in package '$package'"
   return 0
 }
 
diff --git a/platform/initrd/common/boot/svc-up b/platform/initrd/common/boot/svc-up
--- a/platform/initrd/common/boot/svc-up
+++ b/platform/initrd/common/boot/svc-up
@@ -10,11 +10,19 @@ up()
   local is_forced="$3"
   local is_wildcard="$4"
 
-  local is_already_up=''
+  # Sanity check:
+  #   Make sure the service we're trying to start actually exists.
+
+  if ! supervisor_service_exists "$package" "$service"; then
+    warn "Service '$package/$service' doesn't exist"
+    return 1
+  fi
 
   # Automatic service enabling:
   #   If the `-f` or `--force` argument is provided, try to
   #   automatically enable any service that's in the down state.
+
+  local is_already_up=''
 
   if supervisor_is_service_disabled "$package" "$service"; then
     if [ "$is_forced" ]; then
@@ -61,24 +69,26 @@ main()
   require_root
   supervisor_init
 
+  local rv=''
+
   if [ "$#" -le 0 ]; then
     supervisor_list_all_services "$package" | while read service; do
       up "$package" "$service" "$force" 't'
+      local r="$?"; [ "$r" -eq 0 ] || exit "$r"
     done
-    local rv="$?"
-    [ "$rv" -ne 0 ] && return "$rv"
+    rv="$?"
   else
     for service in "$@"; do
       up "$package" "$service" "$force"
+      rv="$?"
     done
   fi
 
-  if [ $# -le 0 ]; then
-    success "Finished starting services in package '$package'"
-  else
-    success "Selected services in package '$package' have started"
+  if [ "$rv" -ne 0 ]; then
+    fatal "Failed to start one or more services in package '$package'"
   fi
 
+  success "Finished starting services in package '$package'"
   return 0
 }
 
