Make error handling uniform across supervisor scripts.
Before this patch, the supervisor scripts had a weird mix of "oh, that service
is already started, I'll just ignore it" and "wait, one of these services is
already stopped, let's freak out". Preconditions were enforced in some areas
more than others.

This patch makes the behavior uniform. If you're operating on a whole package
(read: not supplying a service name on the command line), services that don't
meet a precondition will be skipped over if possible. If you're operating on an
explicit list of services, any precondition violation will cause a fatal error.

Example: I have a package `P` with services `S1`, `S2`, and `S3`. Let's say `S1`
is down, and `S2` and `S3` are both running. In this case, `svc-down P` will do
what you're probably intending: make sure all three of the services end up in
the down state. Conversely, execution of `svc-down P S2 S1` will fail, because
`S1` is already in the down state. Running `svc-down S2 S3` will succeed.

Hopefully this scheme makes sense – scripts can list packages/services
programmatically and target up/down/disable/enable operations surgically,
while humans can concisely say "I just want everything in medic-core to start
running again".

diff --git a/platform/initrd/common/boot/supervisor-disable b/platform/initrd/common/boot/supervisor-disable
--- a/platform/initrd/common/boot/supervisor-disable
+++ b/platform/initrd/common/boot/supervisor-disable
@@ -3,7 +3,7 @@
 source '/boot/include/utility'
 source '/boot/include/supervisor'
 
-down()
+disable()
 {
   local package="$1"
   local service="$2"
@@ -11,18 +11,15 @@ down()
 
   if [ "$is_wildcard" ]; then
     if supervisor_is_service_disabled "$package" "$service"; then
-      warn "Service '$package/$service' is disabled; skipping"
-      return 0
-    elif supervisor_is_service_down "$package" "$service"; then
-      warn "Service '$package/$service' is already down; skipping"
+      warn "Service '$package/$service is already disabled; skipping"
       return 0
     fi
   fi
 
-  supervisor_service_down "$package" "$service" \
-    || fatal "Failed to shut down service '$package/$service'"
+  supervisor_service_disable "$package" "$service" \
+    || fatal "Failed to disable service '$package/$service'"
 
-  info "Service '$package/$service' was stopped successfully"
+  info "Service '$package/$service' was disabled successfully"
   return 0
 }
 
@@ -40,20 +37,22 @@ main()
 
   if [ "$#" -le 0 ]; then
     supervisor_list_all_services "$package" | while read service; do
-      down "$package" "$service" 't'
+      disable "$package" "$service" 't'
     done
-    rv="$?"
-    [ "$rv" -ne 0 ] && return "$rv"
+    local rv="$?"
+    if [ "$rv" -ne 0 ]; then
+      return "$rv"
+    fi
   else
     for service in "$@"; do
-      down "$package" "$service"
+      disable "$package" "$service"
     done
   fi
 
   if [ $# -le 0 ]; then
-    success "Finished stopping services in package '$package'"
+    success "Finished disabling services in package '$package'"
   else
-    success "Selected services in package '$package' have stopped"
+    success "Selected services in package '$package' are now disabled"
   fi
 
   return 0
diff --git a/platform/initrd/common/boot/svc-up b/platform/initrd/common/boot/svc-up
--- a/platform/initrd/common/boot/svc-up
+++ b/platform/initrd/common/boot/svc-up
@@ -7,16 +7,50 @@ up()
 {
   local package="$1"
   local service="$2"
+  local is_forced="$3"
+  local is_wildcard="$4"
 
-  supervisor_service_up "$package" "$service" \
-    || fatal "Failed to start service '$service' in '$package'"
+  local is_already_up=''
 
-  info "Service '$package/$service' started successfully"
+  # Automatic service enabling:
+  #   If the `-f` or `--force` argument is provided, try to
+  #   automatically enable any service that's in the down state.
+
+  if supervisor_is_service_disabled "$package" "$service"; then
+    if [ "$is_forced" ]; then
+      supervisor_service_enable "$package" "$service" \
+        || fatal "Failed to enable service '$package/$service'"
+      is_already_up='t'
+    elif [ "$is_wildcard" ]; then
+      warn "Service '$package/$service' is disabled; skipping"
+      return 0
+    fi
+  fi
+
+  if [ "$is_wildcard" -a -z "$is_already_up" ]; then
+    if ! supervisor_is_service_down "$package" "$service"; then
+      warn "Service '$package/$service' is already up; skipping"
+      return 0
+    fi
+  fi
+
+  if [ -z "$is_already_up" ]; then
+    supervisor_service_up "$package" "$service" \
+      || fatal "Failed to start service '$package/$service'"
+  fi
+
+  info "Service '$package/$service' was started successfully"
   return 0
 }
 
 main()
 {
+  local force=''
+
+  if [ "$1" = '-f' -o "$1" = '--force' ]; then
+    force='t'; shift 1
+  fi
+
   local package="$1"
   shift 1
 
@@ -28,17 +62,19 @@ main()
   supervisor_init
 
   if [ "$#" -le 0 ]; then
-    supervisor_list_down_services "$package" | while read service; do
-      up "$package" "$service"
+    supervisor_list_all_services "$package" | while read service; do
+      up "$package" "$service" "$force" 't'
     done
+    local rv="$?"
+    [ "$rv" -ne 0 ] && return "$rv"
   else
     for service in "$@"; do
-      up "$package" "$service"
+      up "$package" "$service" "$force"
     done
   fi
 
   if [ $# -le 0 ]; then
-    success "All services in package '$package' have started"
+    success "Finished starting services in package '$package'"
   else
     success "Selected services in package '$package' have started"
   fi
@@ -48,7 +84,7 @@ main()
 
 usage()
 {
-  echo "Usage: $0 <package-name> [service-name]..."
+  echo "Usage: $0 [ -f | --force ] <package-name> [service-name]..."
   exit 111
 }
 
