Fix issue blocking boot on upgraded instances

diff --git a/platform/initrd/common/boot/system-start b/platform/initrd/common/boot/system-start
--- a/platform/initrd/common/boot/system-start
+++ b/platform/initrd/common/boot/system-start
@@ -163,8 +163,14 @@ main()
   done
 
   for package_path in /mnt/startup/packages/*.vpkg; do
-    package_update "$package_path" "$is_newly_initialized" \
-      || fatal 'Failed to extract required software from disk/image'
+
+    # Install or update package
+    package_update "$package_path" "$is_newly_initialized"
+
+    # Successful or already-installed
+    if [ "$?" -ne 0 -a "$?" -ne 4 ]; then
+      fatal 'Failed to extract required software from disk/image'
+    fi
 
     finished_packages="$(($finished_packages + 1))"
     local percent_packages="$((100 * $finished_packages / $total_packages))"
