Build system refactor; add compiler to build system.

diff --git a/source/medic-core-1.5.0/scripts/build-all b/source/medic-core-1.5.0/scripts/build-all
--- a/source/medic-core-1.5.0/scripts/build-all
+++ b/source/medic-core-1.5.0/scripts/build-all
@@ -11,7 +11,17 @@ fatal()
 
 source "$base_dir/scripts/include/logger" 2>/dev/null &&
 source "$base_dir/scripts/include/builder" 2>/dev/null \
-    || fatal 'Unable to load a required library'
+  || fatal 'Unable to load a required library'
+
+usage()
+{
+  echo
+  echo "Usage:" >&2
+  echo "  $0 root-directory" >&2
+  echo
+
+  exit 111
+}
 
 main()
 {
@@ -26,16 +36,16 @@ main()
 
   check_args "$@" || usage
 
-  # Processor and system options:
-  #  These are used by `builder_setup_environment` to set
-  #  environment variables and compilation flags appropriately.
-
-  original_platform="$platform"
-  bits="`builder_platform_to_bits "$platform" "$bits"`"
-  architecture="`builder_platform_to_architecture "$platform" "$bits"`"
-
   local uname="`uname -s`"
   local stdarg="--prefix=\"$prefix\""
+
+  builder_initialize &&
+  builder_setup_environment "$prefix" \
+    "$pkg_start" "$pkg_start_version" "$pkg_stop" \
+      "$pkg_stop_version" "$uname" "$architecture" "$bits" "$parallel"
+
+  [ $? -eq 0 ] \
+    || fatal 'Failed to set up build environment'
 
   # Package-specific options:
   #  These are used to vary configuration based upon
@@ -47,11 +57,6 @@ main()
     erlang_extra_options="--enable-m${bits}-build"
   fi
 
-  builder_initialize &&
-  builder_setup_environment "$prefix" \
-    "$pkg_start" "$pkg_start_version" "$pkg_stop" \
-      "$pkg_stop_version" "$uname" "$architecture" "$bits" "$parallel" &&
-  \
   build_autoconf 'pv' "$stdarg" &&
   \
   (disable_parallelism && simple_cflags &&
@@ -258,27 +263,11 @@ remove_library_executable_bits()
     \( -name '*.so.*' -o -name '*.la' \) -type f -exec chmod +x {} \;
 }
 
-fatal()
-{
-  echo "$0: fatal: $*" >&2
-  exit 1
-}
-
 check_args()
 {
   local prefix="$1"
 
   [ -d "$prefix" ] 
-}
-
-usage()
-{
-  echo
-  echo "Usage:" >&2
-  echo "  $0 root-directory" >&2
-  echo
-
-  exit 111
 }
 
 cd "$base_dir/source" && main "$@"
diff --git a/source/medic-core-1.5.0/scripts/include/builder b/source/medic-core-1.5.0/scripts/include/builder
--- a/source/medic-core-1.5.0/scripts/include/builder
+++ b/source/medic-core-1.5.0/scripts/include/builder
@@ -1,8 +1,28 @@
 #!/bin/bash
 
+prepend_path()
+{
+  for dir in "$@"; do
+    export PATH="$dir/bin:$PATH"
+    export LD_LIBRARY_PATH="$dir/lib:$LD_LIBRARY_PATH"
+    export DYLD_LIBRARY_PATH="$dir/lib:$DYLD_LIBRARY_PATH"
+    export PKG_CONFIG_PATH="$dir/lib/pkgconfig:$PKG_CONFIG_PATH"
+  done
+}
+
+append_path()
+{
+  for dir in "$@"; do
+    export PATH="$PATH:$dir/bin"
+    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$dir/lib"
+    export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$dir/lib"
+    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$dir/lib/pkgconfig"
+  done
+}
+
 log()
 {
-  logger "$1" "$original_platform"
+  logger "$1" "$platform"
 }
 
 disable_parallelism()
@@ -90,6 +110,23 @@ build_config()
     && sh -c "$MAKE install $make_install_args") 2>&1 | log "$name"
   
   builder_check_status "$name" "${PIPESTATUS[0]}"
+}
+
+builder_normalize_platform()
+{
+  local platform="$1"
+
+  if [[ "$platform" = x86_64* ]]; then
+    rv='x64'
+  elif [[ "$platform" = x86* ]]; then
+    rv='x86'
+  elif [[ "$platform" = i?86 ]]; then
+    rv='x86'
+  else
+    rv='x86'
+  fi
+
+  echo "$rv"
 }
 
 builder_platform_to_architecture()
@@ -507,20 +544,19 @@ builder_setup_environment()
   export CXX='g++'
   export MAKE='gmake'
   export GNUMAKE='gmake'
-  export PATH="$prefix/bin:$PATH"
+
   export INITIAL_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
-  export LD_LIBRARY_PATH="$prefix/lib:$LD_LIBRARY_PATH"
   export INITIAL_DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH"
-  export DYLD_LIBRARY_PATH="$prefix/lib:$DYLD_LIBRARY_PATH"
-  export PKG_CONFIG_PATH="$prefix/lib/pkgconfig"
+
+  prepend_path "$prefix"
 
   builder_detect_system \
     || fatal 'Unsupported system; please edit Makefile'
 
-	if [ "$bits" -eq 64 ]; then
-	  (cd "$prefix" && rm -rf lib64 && mkdir -p lib && ln -s lib lib64) \
-	    || fatal 'Failed to create symbolic link for 64-bit libraries'
-	fi
+  if [ "$bits" -eq 64 ]; then
+    (cd "$prefix" && rm -rf lib64 && mkdir -p lib && ln -s lib lib64) \
+      || fatal 'Failed to create symbolic link for 64-bit libraries'
+  fi
 
   if [ "$parallel" ]; then
     export MAKE="$MAKE -j$parallel"
@@ -549,13 +585,29 @@ builder_setup_environment()
 
 builder_detect_system()
 {
-  # Detect machine word size
+  # Ensure `uname` is set
+  if [ -z "$uname" ]; then
+    uname="`uname -s`"
+  fi
+
+  # Ensure `platform` is set
+  if [ -z "$platform" ]; then
+    local machine="`uname -m`"
+    platform="`builder_normalize_platform "$machine"`"
+  fi
+
+  # Guess machine word size if necessary
   if [ -z "$bits" ]; then
-    if [ "`uname -m | grep 64$`" ]; then
+    if [ "`echo "$platform" | grep 64$`" ]; then
       bits='64'
     else
       bits='32'
     fi
+  fi
+
+  # Ensure architecture is set
+  if [ -z "$architecture" ]; then
+    architecture="`builder_platform_to_architecture "$platform"`"
   fi
 
   # Detect architecture/platform
diff --git a/source/vm-tools-9.4.0/scripts/build-all b/source/vm-tools-9.4.0/scripts/build-all
--- a/source/vm-tools-9.4.0/scripts/build-all
+++ b/source/vm-tools-9.4.0/scripts/build-all
@@ -19,28 +19,23 @@ main()
   local parallel="$8"
   local kernel_version="$9"
 
-  local kernel_module_path="`
-    readlink -f "${10}" 2>/dev/null || realpath "${10}"
-  `"
-
   check_args "$@" || usage
-
-  # Processor and system options:
-  #  These are used by `builder_setup_environment` to set
-  #  environment variables and compilation flags appropriately.
-
-  original_platform="$platform"
-  bits="`builder_platform_to_bits "$platform" "$bits"`"
-  architecture="`builder_platform_to_architecture "$platform" "$bits"`"
 
   local uname="`uname -s`"
   local stdarg="--prefix=\"$prefix\""
 
+  local kernel_module_path="`
+    readlink -f "${10}" 2>/dev/null || realpath "${10}"
+  `"
+
   builder_initialize &&
   builder_setup_environment "$prefix" \
     "$pkg_start" "$pkg_start_version" "$pkg_stop" \
-      "$pkg_stop_version" "$uname" "$architecture" "$bits" "$parallel" &&
-  \
+      "$pkg_stop_version" "$uname" "$architecture" "$bits" "$parallel"
+
+  [ $? -eq 0 ] \
+    || fatal 'Failed to set up build environment'
+
   build_autoconf 'pv' "$stdarg" &&
   \
   (disable_parallelism && simple_cflags &&
