Merge branch 'dev' in to branch 'master'.

diff --git a/packages/medic-core/scripts/medic-core/private/gammu-autodetect b/packages/medic-core/scripts/medic-core/private/gammu-autodetect
--- a/packages/medic-core/scripts/medic-core/private/gammu-autodetect
+++ b/packages/medic-core/scripts/medic-core/private/gammu-autodetect
@@ -17,27 +17,54 @@ detect()
   local settings_file="$settings_dir/autodetect.conf"
   
   local logs_dir="$storage_dir/logs"
-  local log="$logs_dir/autodetect.log"
-  
-  for i in `seq 0 9`; do
+  local log="$logs_dir/gammu-autodetect.log"
+
+  for device_path in $GAMMU_SMS_DEVICES; do 
+
+    if ! [ -c "$device_path" ]; then
+      continue
+    fi
+    
+    local device_name="`basename "$device_path"`"
+
+    # Probe for device:
+    #   Re-create configuration file, then attempt to identify device.
 
     rm -f "$settings_file" && mkdir -p "$logs_dir" &&
-    echo "Auto-detect running for '/dev/ttyUSB$i' at `date`" >> "$log" &&
+    warn "Auto-detect running for '$device_path'" &&
     \
-    sed "s/ttyUSBX/ttyUSB$i/g;" < "$settings_file.template" \
+    sed "s/ttyUSBX/$device_name/g;" < "$settings_file.template" \
       > "$settings_file" 2>/dev/null &&
     \
     gammu -c "$settings_file" identify >> "$log" 2>&1
 
     if [ "$?" -eq 0 ]; then
-      local device="/dev/ttyUSB$i"
-      chown "$user:$user" "$device"
-      echo "$device"
+
+      # Take ownership and return full device path
+      chown "$user:$user" "$device_path" && echo "$device_path"
+
+      if [ "$?" -ne 0 ]; then
+        warn "Failed to take ownership of '$device_path'"
+        warn "Skipping device; continuing auto-detection"
+        return 2
+      fi
+
       return 0
-    fi;
-   done
+    fi
+  done
 
   return 1
+}
+
+warn()
+{
+  echo "`date`: Warning: $*" >&2
+}
+
+fatal()
+{
+  echo "`date`: Fatal: $*" >&2
+  exit 1
 }
 
 main()
diff --git a/packages/medic-core/scripts/medic-core/private/gammu-monitor b/packages/medic-core/scripts/medic-core/private/gammu-monitor
--- a/packages/medic-core/scripts/medic-core/private/gammu-monitor
+++ b/packages/medic-core/scripts/medic-core/private/gammu-monitor
@@ -11,10 +11,18 @@ monitor()
   local package='medic-core'
   local service='gammu'
   
+  local last_device=''
   local settings_dir="/srv/storage/$package/$service/monitor"
+
+  # Clean up:
+  #  These files might be left-over from a previous boot.
+
+  rm -f "$settings_dir/detected" "$settings_dir/detecting" &&
   mkdir -p "$settings_dir"
 
-  local last_device=''
+  # Main loop:
+  #  Find the device that's currently in use. If it changes or
+  #  goes away entirely, log the event and probe for a new one.
  
   while true; do
     local device="`"$base/gammu-status" gammu`"
@@ -23,21 +31,31 @@ monitor()
       rm -f "$settings_dir/detected"
       
       if [ "$last_device" ]; then
-        echo "Device '$last_device' was lost at `date`" >&2
+        warn "Device '$last_device' was lost"
       fi
       
       "$base/gammu-status" &>/dev/null
 
       if [ "$?" -eq 0 ]; then
+
         touch "$settings_dir/detecting"
-        echo "Possible device(s) found, running autodetection at `date`" >&2
+        warn 'Possible device(s) found, running autodetection'
 
         device="`"$base/gammu-autodetect"`"
       
         if [ "$device" ]; then
-          echo "$device" > "$settings_dir/detected"
-          echo "Auto-detect found device '$device' at `date`" >&2
+          warn "Auto-detection found device '$device'"
+          warn "Reloading '$package/$service' to add new device(s)..."
+
+          echo "$device" > "$settings_dir/detected" &&
+          /boot/svc-reload "$package" "$service"
+
+          if [ "$?" -ne 0 ]; then
+            rm -f "$settings_dir/detected"
+            warn "Failed to restart '$package/$service'"
+          fi
         fi
+
       fi
       
       rm -f "$settings_dir/detecting"
@@ -48,6 +66,17 @@ monitor()
   done
   
   return 1
+}
+
+warn()
+{
+  echo "`date`: Warning: $*" >&2
+}
+
+fatal()
+{
+  echo "`date`: Fatal: $*" >&2
+  exit 1
 }
 
 main()
