Packaging code: prefix all functions with the module name, as we do in supervisor.

diff --git a/initrd/boot/package-install b/initrd/boot/package-install
--- a/initrd/boot/package-install
+++ b/initrd/boot/package-install
@@ -8,6 +8,11 @@ main()
     usage
   fi
 
+  for path in "$@"; do
+    package_install "$path" \
+      || fatal "Failed to install package '$path'"
+  done
+
   return 0
 }
 
diff --git a/initrd/boot/package-remove b/initrd/boot/package-remove
--- a/initrd/boot/package-remove
+++ b/initrd/boot/package-remove
@@ -8,6 +8,11 @@ main()
     usage
   fi
 
+  for package in "$@"; do
+    package_remove "$package" \
+      || fatal "Failed to remove package '$package'"
+  done
+
   return 0
 }
 
diff --git a/initrd/boot/package-update b/initrd/boot/package-update
--- a/initrd/boot/package-update
+++ b/initrd/boot/package-update
@@ -8,6 +8,11 @@ main()
     usage
   fi
 
+  for package in "$@"; do
+    package_update "$package" \
+      || fatal "Failed to update package '$package'"
+  done
+
   return 0
 }
 
