Work in progress: improvements to the package format and the package installation/update/removal code.

diff --git a/initrd/boot/system-start b/initrd/boot/system-start
--- a/initrd/boot/system-start
+++ b/initrd/boot/system-start
@@ -1,7 +1,6 @@
 #!/bin/sh
 
-local log='/var/log/start.log'
-
+source '/boot/include/logger'
 source '/boot/include/cursor'
 source '/boot/include/startup'
 source '/boot/include/package'
@@ -95,11 +94,23 @@ main()
 
   echo "Software update started at `date`" >> "$log" 2>&1
 
-  update_package 'system-services' "$is_newly_initialized" >> "$log" 2>&1 &&
-  update_package 'medic-core' "$is_newly_initialized" >> "$log" 2>&1 &&
-  update_package 'concierge' "$is_newly_initialized" >> "$log" 2>&1 &&
-  update_package 'java' "$is_newly_initialized" >> "$log" 2>&1 \
-    || fatal 'Failed to extract required software from ISO image'
+  local total_packages='0'
+  local finished_packages='0'
+
+  for package_path in /mnt/image/packages/*.vpkg; do
+    total_packages="$(($total_packages + 1))"
+  done
+
+  for package_path in /mnt/image/packages/*.vpkg; do
+    update_package "$package_path" "$is_newly_initialized" \
+      || fatal 'Failed to extract required software from ISO image'
+
+    finished_packages="$(($finished_packages + 1))"
+    local percent_packages="$((100 * $finished_packages / $total_packages))"
+
+    display_centered "Setting up software ($percent_packages% complete)..."
+
+  done
 
   echo "Software update finished at `date`" >> "$log" 2>&1
   display_centered 'Checking authentication database...'
@@ -146,7 +157,7 @@ fatal()
 {
   clear
   echo -ne '\n\n'
-  echo 'A serious error has occurred.' >&2
+  echo 'An unrecoverable error has occurred.' >&2
   echo 'The virtual machine cannot start properly at this time.' >&2
   echo "Details: $*." >&2
   echo >&2
