Always run package setup tasks
When booting an older or equal-to-installed base image, the
package setup scripts must be run. They cannot be skipped.

diff --git a/platform/initrd/common/boot/include/package b/platform/initrd/common/boot/include/package
--- a/platform/initrd/common/boot/include/package
+++ b/platform/initrd/common/boot/include/package
@@ -290,11 +290,27 @@ package_remove()
   return 0
 }
 
+package_update_run_setup()
+{
+  local package="$1"
+
+  log "Running setup tasks for package '$package'"
+
+  if ! package_setup "$package"; then
+    warn "At least one setup script in package '$package' failed"
+    warn "Your installation of '$package' may be incomplete"
+    return 17
+  fi
+
+  return 0
+}
+
 package_update()
 {
   local path="$1"
   local force_install="$2"
   local use_soft_restart="$3"
+  local setup_on_version_match="$4"
 
   local package="`package_extract_name "$path"`" &&
   local v_new="`package_extract_version "$path"`" &&
@@ -324,7 +340,10 @@ package_update()
   fi
 
   if [ "$v_prev" -ge "$v_new" ]; then
-    if [ -z "$force_install" ]; then
+    if [ "$setup_on_version_match" ]; then
+      package_update_run_setup "$package"
+      return "$?"
+    elif [ -z "$force_install" ]; then
       warn "An equal-or-greater version of '$package' is already installed"
       warn "Use the -f/--force option if you want to install it anyway"
       return 4
@@ -350,13 +369,7 @@ package_update()
     return 6
   fi
 
-  log "Running setup tasks for package '$package'"
-
-  if ! package_setup "$package"; then
-    warn "At least one setup script in package '$package' failed"
-    warn "Your installation of '$package' may be incomplete"
-    return 17
-  fi
+  package_update_run_setup "$package"
 
   if [ "$use_soft_restart" ]; then
     info "Restarting services for package '$package'..."
