Temporarily enable setup script output
This changeset makes output from package setup scripts visible when
installing/updating packages from the command line.

Some future work needs to be done to ensure this sort of output is
displayed to an interactive user, hidden from a noninteractive user,
and always logged persistently to disk. We likely need to replace
the `&> "$log"` target with a pipe-based target like `| "$log_cmd" 2>&1`,
pick a location for system-level output that's not otherwise captured
by a script, and then make sure we don't leak any output to the
system console. This can be put off for a bit.

diff --git a/platform/initrd/common/boot/include/package b/platform/initrd/common/boot/include/package
--- a/platform/initrd/common/boot/include/package
+++ b/platform/initrd/common/boot/include/package
@@ -427,15 +427,15 @@ package_setup()
   local package="`basename -- "$1"`"
 
   for script in "$srv_dir/scripts/$package/setup"/*; do
-    if [ -x "$script" ]; then
+    if ! [ -x "$script" ]; then
+      continue
+    fi
 
-      local task_name="$package/`basename -- "$script"`"
-      log "Running setup task '$task_name'"
+    local task_name="$package/`basename -- "$script"`"
+    info "Running setup task '$task_name'"
 
-      "$script" >> "$log" 2>&1 \
-        || warn "Setup task '$task_name' was not successful"
-      
-      log "Finished setup task '$task_name'"
+    if ! "$script"; then
+      warn "Setup task '$task_name' failed to complete"
     fi
   done
 
