Script refactor WIP: input sanitization, manifests
Always explicitly sanitize package and service names to avoid path
traversal vulnerabilities. Refactoring toward use of package manifest
information during update and removal operations.

diff --git a/platform/initrd/common/boot/include/package b/platform/initrd/common/boot/include/package
--- a/platform/initrd/common/boot/include/package
+++ b/platform/initrd/common/boot/include/package
@@ -7,6 +7,22 @@ receipts_dir="$srv_dir/system/storage/receipts"
 settings_dir="$srv_dir/system/settings/packages"
 supervisor_dir="$srv_dir/system/storage/supervisor"
 
+package_sanitize_name()
+{
+  local package="$1"
+
+  basename -- "$package"
+  return "$?"
+}
+
+service_sanitize_name()
+{
+  local service="$1"
+
+  basename -- "$service"
+  return "$?"
+}
+
 package_extract_metadata()
 {
   local path="$1"
@@ -54,6 +70,30 @@ package_retrieve_installed_version()
   local package="$1"
 
   cat "$receipts_dir/$package/version" 2>/dev/null
+  return "$?"
+}
+
+package_is_installed()
+{
+  local package="$1"
+
+  test -f "$receipts_dir/$package/version" 2>/dev/null
+  return "$?"
+}
+
+package_manifest_copy()
+{
+  local package="$1"
+
+  local version="`package_retrieve_installed_version "$package"`" \
+    || return 1
+
+  local manifest_path="$receipts_dir/$package/manifest"
+  local new_manifest_path="$manifest_path.$version"
+
+  cp -af "$manifest_path" "$new_manifest_path" &&
+  echo "$new_manifest_path"
+
   return "$?"
 }
 
@@ -110,6 +150,14 @@ package_install()
     log "File '$srv_dir/scripts/$package/install' is not executable"
   fi
 
+  log "Running setup tasks for package '$package'"
+
+  if ! package_setup "$package"; then
+    warn "At least one setup script in package '$package' failed"
+    warn "Your installation of '$package' may be incomplete"
+    return 6
+  fi
+
   supervisor_start "$package"
   local rv="$?"
 
@@ -117,7 +165,7 @@ package_install()
     info "Package '$package' has no services to start; continuing"
   elif [ "$rv" -ne 0 ]; then
     warn "Failed to start services for package '$package'"
-    return 6
+    return 7
   fi
 
   log "Successfully installed package '$package'"
@@ -152,8 +200,7 @@ package_remove()
     fi
   fi
 
-  rm -rf "$receipts_dir/$package" \
-    "$supervisor_dir/$package" "$settings_dir/$package"
+  package_remove_manifest "$package"
 
   if [ "$?" -gt 0 ]; then
     warn "Failed to remove installation records for package '$package'"
@@ -164,6 +211,16 @@ package_remove()
   sync
 
   return 0
+}
+
+package_remove_manifest()
+{
+  local package="$1"
+
+  rm -rf "$receipts_dir/$package" \
+    "$supervisor_dir/$package" "$settings_dir/$package"
+
+  return "$?"
 }
 
 package_update()
@@ -192,7 +249,7 @@ package_update()
     if [ "$v_prev" -gt "$v_new" -a -z "$force_install" ]; then
 
       warn "A newer version of '$package' is already installed"
-      warn "Use the force-install option if you want to install it anyway"
+      warn "Use the -f/--force option if you want to install it anyway"
       return 3
 
     elif [ "$v_prev" -lt "$v_new" ] 2>/dev/null; then
@@ -206,18 +263,17 @@ package_update()
       fi
     else
       warn "Version '$v_prev' of package '$package' is already installed"
+      return 5
     fi
   else
-    force_install='t'
-    log "Package '$package' is not installed yet; installing"
+    warn "Package '$package' is not installed"
+    return 6
   fi
 
-  if [ "$force_install" ]; then
-    log "Installing package '$package'"
-    if ! package_install "$path"; then
-      warn "Package '$package' encountered an error during installation"
+  if ! package_update_twophase "$package" "$path"; then
+    warn "Error encountered while updating package '$package'"
       warn "Software installation from file '$file' was unsuccessful"
-      return 5
+      return 7
     fi
   fi
 
@@ -226,11 +282,22 @@ package_update()
   if ! package_setup "$package"; then
     warn "At least one setup script in package '$package' failed"
     warn "Your installation of '$package' may be incomplete"
-    return 6
+    return 8
   fi
 
   log "Finished examining package '$package'"
   return 0
+}
+
+package_update_twophase()
+{
+  local package="$1"
+  local path="$2"
+
+  local manifest="`package_manifest_copy "$package"`" \
+    || return 1
+
+  return "$?"
 }
 
 package_merge_environment()
diff --git a/platform/initrd/common/boot/package-install b/platform/initrd/common/boot/package-install
--- a/platform/initrd/common/boot/package-install
+++ b/platform/initrd/common/boot/package-install
@@ -14,17 +14,30 @@ main()
   require_root
   supervisor_init
 
+  local force_install=''
+
+  if [ "$1" = '-f' -o "$1" = '--force' ]; then
+    force_install='t'
+    shift 1
+  fi
+
+
   for path in "$@"; do
     local package="`package_extract_name "$path"`" \
       || fatal "Failed to determine name of package '$path'"
 
+    package="`package_sanitize_name "$package"`" \
+      || fatal "Package '$path' contains invalid name '$package'"
+
+    if [ -z "$force_install" ]; then
+      if package_is_installed "$package"; then
+        fatal "Package '$package' is already installed"
+      fi
+    fi
+
     package_install "$path" \
       || fatal "Failed to install package '$path'"
 
-    package_setup "$package" \
-      || fatal "Failed to run setup script for package '$path'"
-
-    supervisor_start "$package"
     local rv="$?"
 
     if [ "$rv" -eq 253 ]; then
@@ -42,7 +55,7 @@ main()
 
 usage()
 {
-  echo "Usage: $0 <package.vpkg>..." >&2
+  echo "Usage: $0 [-f | --force] <package.vpkg>..." >&2
   exit 111
 }
 
diff --git a/platform/initrd/common/boot/supervisor-inspect b/platform/initrd/common/boot/supervisor-inspect
--- a/platform/initrd/common/boot/supervisor-inspect
+++ b/platform/initrd/common/boot/supervisor-inspect
@@ -42,14 +42,18 @@ main()
   supervisor_init
 
   for package in "$@"; do
-    local package="`basename -- "$package"`"
+    package="`package_sanitize_name "$package"`" \
+      || fatal "Invalid package name '$package'"
+
     supervisor_package_exists "$package" \
       || fatal "Package '$package' doesn't appear to be installed"
   done
 
   if [ "$#" -gt 0 ]; then
     echo && for package in "$@"; do
-      local package="`basename -- "$package"`"
+      package="`package_sanitize_name "$package"`" \
+        || fatal "Invalid package name '$package'"
+
       show_package "$package"
       show_services "$package"
     done
diff --git a/platform/initrd/common/boot/supervisor-list b/platform/initrd/common/boot/supervisor-list
--- a/platform/initrd/common/boot/supervisor-list
+++ b/platform/initrd/common/boot/supervisor-list
@@ -17,7 +17,7 @@ usage()
 
 main()
 {
-  local package="`basename -- "$1"`"
+  local package="$1"
   local attribute="$2"
 
   if [ "$1" = '-h' -o "$1" = '--help' ]; then
@@ -30,6 +30,9 @@ main()
   if [ -z "$package" -o "$package" = 'all' ]; then
     supervisor_list_all_packages
   else
+    package="`package_sanitize_name "$package"`" \
+      || fatal "Invalid package name '$package'"
+
     if ! supervisor_package_exists "$package"; then
       fatal "Package '$package' is not currently installed"
     fi
diff --git a/platform/initrd/common/boot/supervisor-stop b/platform/initrd/common/boot/supervisor-stop
--- a/platform/initrd/common/boot/supervisor-stop
+++ b/platform/initrd/common/boot/supervisor-stop
@@ -15,6 +15,9 @@ main()
   local package="$1"
   shift 1
 
+  package="`package_sanitize_name "$package"`" \
+    || fatal "Invalid package name '$package'"
+
   local is_failure=''
 
   # Strict mode:
@@ -24,6 +27,9 @@ main()
 
   if [ "$#" -gt 0 ]; then
     for service in "$@"; do
+      service="`service_sanitize_name "$service"`" \
+        || fatal "Invalid service name '$service'"
+
       if supervisor_is_service_disabled "$package" "$service"; then
         is_failure='t'
         warn "Service '$package/$service' is disabled"
diff --git a/platform/initrd/common/boot/svc-down b/platform/initrd/common/boot/svc-down
--- a/platform/initrd/common/boot/svc-down
+++ b/platform/initrd/common/boot/svc-down
@@ -45,6 +45,9 @@ main()
   require_root
   supervisor_init
 
+  package="`package_sanitize_name "$package"`" \
+    || fatal "Invalid package name '$package'"
+
   local rv=''
 
   if [ "$#" -le 0 ]; then
@@ -55,6 +58,9 @@ main()
     rv="$?"
   else
     for service in "$@"; do
+      service="`service_sanitize_name "$service"`" \
+        || fatal "Invalid service name '$service'"
+
       down "$package" "$service"
       rv="$?"
     done
diff --git a/platform/initrd/common/boot/svc-reload b/platform/initrd/common/boot/svc-reload
--- a/platform/initrd/common/boot/svc-reload
+++ b/platform/initrd/common/boot/svc-reload
@@ -35,6 +35,9 @@ main()
   require_root
   supervisor_init
 
+  package="`package_sanitize_name "$package"`" \
+    || fatal "Invalid package name '$package'"
+
   local rv=''
 
   if [ "$#" -le 0 ]; then
@@ -45,6 +48,9 @@ main()
     rv="$?"
   else
     for service in "$@"; do
+      service="`service_sanitize_name "$service"`" \
+        || fatal "Invalid service name '$service'"
+
       reload "$package" "$service"
       rv="$?"
     done
diff --git a/platform/initrd/common/boot/svc-restart b/platform/initrd/common/boot/svc-restart
--- a/platform/initrd/common/boot/svc-restart
+++ b/platform/initrd/common/boot/svc-restart
@@ -45,6 +45,9 @@ main()
   require_root
   supervisor_init
 
+  package="`package_sanitize_name "$package"`" \
+    || fatal "Invalid package name '$package'"
+
   local rv=''
 
   if [ "$#" -le 0 ]; then
@@ -56,6 +59,9 @@ main()
     [ "$rv" -ne 0 ] && return "$rv"
   else
     for service in "$@"; do
+      service="`service_sanitize_name "$service"`" \
+        || fatal "Invalid service name '$service'"
+
       restart "$package" "$service"
       rv="$?"
     done
