Use sticky bit on files to ignore during removal
This is a bit of a hack, but I'm going to try it out: use the
sticky bit on files to denote that they've been modified locally
and shouldn't be auto-removed by the package management system.
May reverse this back out later if it's not useful, is too
unwieldly, or there ends up being a better way to do it.

diff --git a/platform/initrd/common/boot/include/package b/platform/initrd/common/boot/include/package
--- a/platform/initrd/common/boot/include/package
+++ b/platform/initrd/common/boot/include/package
@@ -118,8 +118,10 @@ package_manifest_remove_all()
   manifest_find_all "$manifest_path" \
     | manifest_filter 'file' | while read file; do
 
-    if ! rm -f "$file" &>/dev/null; then
-      warn "Unable to remove file '$srv_dir/$file'"
+    if ! [ -k "$file" ]; then
+      if ! rm -f "$file" &>/dev/null; then
+        warn "Unable to remove file '$srv_dir/$file'"
+      fi
     fi
   done
 
@@ -150,8 +152,10 @@ package_manifest_remove_differential()
   manifest_find_removed "$manifest_previous" "$manifest_current" \
     | manifest_filter 'file' | while read file; do
 
-    if ! rm -f "$file" &>/dev/null; then
-      warn "Unable to remove file '$srv_dir/$file'"
+    if ! [ -k "$file" ]; then
+      if ! rm -f "$file" &>/dev/null; then
+        warn "Unable to remove file '$srv_dir/$file'"
+      fi
     fi
   done
 
