Initial check-in: Use eudev, kernel 3.14.35.
Kernel update is currently x64-only; leaving it masked off until the x86
configuration is checked in. All of this still needs substantial testing.

diff --git a/platform/source/medic-core-1.6.0/scripts/build-all b/platform/source/medic-core-1.6.0/scripts/build-all
--- a/platform/source/medic-core-1.6.0/scripts/build-all
+++ b/platform/source/medic-core-1.6.0/scripts/build-all
@@ -95,15 +95,21 @@ main()
   \
   if [ "$build_platform" = 'linux-elf' ]; then
 
+    local initrd_prefix="`readlink -f "../../../initrd/$platform"`" \
+      || fatal 'Unable to locate initrd directory'
+
     build_make_install 'libutempter' "$prefix" \
       "DESTDIR=\"$prefix\" libdir=/lib \
-        libexecdir=/lib includedir=/include mandir=/man" &&
+       libexecdir=/lib includedir=/include mandir=/man" &&
     \
     builder_remove_static_libraries 'utempter' &&
     \
     build_autoconf 'screen' "$stdarg" &&
     build_autoconf 'strace' "$stdarg" &&
-    build_autoconf 'usbutils' "$stdarg" &&
+    \
+    build_autoconf 'usbutils' \
+      "$stdarg UDEV_CFLAGS=\"-I$initrd_prefix/usr/include\" \
+       UDEV_LIBS=\"-L$initrd_prefix/lib -l:libudev.so.1\"" &&
     \
     (disable_parallelism && build_make 'usb-modeswitch' \
      'install-static' "DESTDIR=\"$prefix\" PREFIX=\"$prefix\"" 'y') &&
