Create a database for read-only replicas
We do this using the backend-direct single user mode of `postgres`,
so as to not have to worry about adding post-service-start hooks
or racing with the backend to start up.

With this change, the `medic-couch2pg` package is now functional.

diff --git a/platform/packages/medic-rdbms/scripts/medic-rdbms/install b/platform/packages/medic-rdbms/scripts/medic-rdbms/install
--- a/platform/packages/medic-rdbms/scripts/medic-rdbms/install
+++ b/platform/packages/medic-rdbms/scripts/medic-rdbms/install
@@ -159,7 +159,32 @@ initialize_cluster()
   "
 
   su - "$user" -c "$command"
-  return "$?"
+
+  if [ "$?" -ne 0 ]; then
+    warn 'Database cluster initialization failed'
+    return 4
+  fi
+
+  local command="
+    '$PACKAGE_ROOT/bin/postgres' \
+      --single -D '$data_dir' template1
+  "
+  
+  local create_sql="
+    create database medic encoding = 'UTF-8';
+  "
+
+  local backend_output="`
+    echo "$create_sql" \
+      | su - "$user" -c "$command" 2>&1 >/dev/null
+  `"
+
+  if [ ! -z "$backend_output" ]; then
+    warn 'Failed to create initial database'
+    return 5
+  fi
+
+  return 0
 }
 
 install "$@"
