Add AMI registration code.

diff --git a/scripts/build-ebs-image b/scripts/build-ebs-image
--- a/scripts/build-ebs-image
+++ b/scripts/build-ebs-image
@@ -8,7 +8,7 @@ fatal()
 
 usage()
 {
-  echo "Usage: $0 loopback_image description device"
+  echo "Usage: $0 platform loopback_image description device"
   exit 1
 }
 
@@ -42,20 +42,39 @@ wait_for_snapshot_availability()
 
 main()
 {
-  local image="$1"
-  local description="$2"
-  local device="$3"
+  local platform="$1"
+  local image="$2"
+  local description="$3"
+  local device="$4"
+
+  if [ "$1" = '-h' -o "$1" = '--help' ]; then
+    usage
+  fi
+
+  local aki=''
+  local architecture=''
+
+  case "$platform" in
+    x64)
+      aki='aki-fc37bacc'
+      architecture='x86_64' ;;
+    x86)
+      aki='aki-fa37baca'
+      architecture='i386' ;;
+    *)
+      fatal "Unsupported platform '$platform'" ;;
+  esac
 
   if ! [ -f "$image" ]; then
-    usage
+    fatal "Unable to locate Xen image '$image'"
   fi
 
   if [ -z "$description" ]; then
-    usage
+    fatal "An image description must be specified"
   fi
 
-  if [ -z "$device" ]; then
-    usage
+  if [ -z "$device" -o -e "$device" ]; then
+    fatal "A not-yet-existing block-special device must be specified"
   fi
 
   local volume_id="`
@@ -70,6 +89,7 @@ main()
   `" -d "$device" &>/dev/null || fatal 'Failed to attach temporary volume'
 
   echo "Volume identifier: $volume_id" >&2
+  echo -n 'Building EBS system image... ' >&2
 
   wait_for_device "$device" \
     || fatal 'Volume did not attach during timeout period'
@@ -94,12 +114,32 @@ main()
   ec2-detach-volume --region "$EC2_REGION" "$volume_id" &>/dev/null \
     || fatal 'Failure while detaching volume'
 
+  echo 'done.' >&2
+  echo -n 'Creating EBS snapshot... ' >&2
+
   local snapshot_id="`
     ec2-create-snapshot "$volume_id" \
       --region "$EC2_REGION" -d "$description" | cut -f2 \
   `" || fatal "Failure while creating snapshot for volume '$volume_id'"
 
   wait_for_snapshot_availability "$snapshot_id"
+  
+  echo 'done.' >&2
+  echo "Snapshot identifier: $snapshot_id"
+
+  echo -n 'Registering AMI... ' >&2
+
+  local ami_id="`
+    ec2-register -a "$architecture" -n "$description" \
+      --kernel "$aki" --root-device-name /dev/sda1 \
+      -d "$description" -s "$snapshot_id" -b '/dev/sdb=:10:false' | cut -f2 \
+  `" || fatal "Failure while registering AMI using snapshot '$snapshot_id'"
+
+  echo 'done.' >&2
+  echo "AMI identifier: $ami_id"
+
+  ec2-create-tags "$ami_id" --tag "Name=MMVA $platform" \
+    || fatal "Failure while setting tags on AMI '$ami_id'"
 
   echo -n "Deleting temporary volume '$volume_id'... " >&2
 
@@ -107,7 +147,6 @@ main()
     || fatal "Failure while deleting volume '$volume_id'"
 
   echo 'done.' >&2
-  echo "Snapshot identifier: $snapshot_id"
 }
 
 main "$@"
