Toward fully-automated builds of MMVA on Amazon EC2.

diff --git a/scripts/build-ebs-image b/scripts/build-ebs-image
--- a/scripts/build-ebs-image
+++ b/scripts/build-ebs-image
@@ -30,14 +30,14 @@ wait_for_volume_availability()
 {
   local volume_id="$1"
 
-  sleep 15
+  sleep 20
 }
 
 wait_for_snapshot_availability()
 {
   local snapshot_id="$1"
 
-  sleep 15
+  sleep 20
 }
 
 main()
@@ -67,9 +67,9 @@ main()
 
   ec2-attach-volume "$volume_id" -i "`
     ec2-metadata -i | cut -d: -f2 | sed 's/^ *//'
-  `" -d "$device" &>/dev/null || fatal 'Failed to attach volume'
+  `" -d "$device" &>/dev/null || fatal 'Failed to attach temporary volume'
 
-  echo "$volume_id" >&2
+  echo "Volume identifier: $volume_id" >&2
 
   wait_for_device "$device" \
     || fatal 'Volume did not attach during timeout period'
@@ -99,10 +99,13 @@ main()
 
   wait_for_snapshot_availability "$snapshot_id"
 
+  echo -n "Deleting temporary volume '$volume_id'... " >&2
+
   ec2-delete-volume "$volume_id" &>/dev/null \
     || fatal "Failure while deleting volume '$volume_id'"
 
-  echo "$snapshot_id"
+  echo 'done.' >&2
+  echo "Snapshot identifier: $snapshot_id"
 }
 
 main "$@"
