Merge changes from EC2 automated build testing.

diff --git a/scripts/launch-ec2-build b/scripts/launch-ec2-build
--- a/scripts/launch-ec2-build
+++ b/scripts/launch-ec2-build
@@ -1,9 +1,29 @@
 #!/bin/sh
 
 fatal() {
+
   echo >&2
   echo "Fatal: $@" >&2
   exit 111
+}
+
+usage() {
+
+  local app="`basename "$0"`"
+  echo "Usage: $app settings_path [ platform [ instance_type ] ]" >&2
+  exit 1
+}
+
+ssh_command() {
+
+  local host="$1"
+  local identity="$2"
+  local remote_command="$3"
+
+  ssh -o StrictHostKeyChecking=no -o RequestTTY=yes \
+    -i "$identity" "$host" "$remote_command"
+
+  return "$?"
 }
 
 main() {
@@ -19,6 +39,10 @@ main() {
   local mmva_url='https://scri.pt/get/mmva'
   local vm_url='https://github.com/browndav/vm-toaster'
 
+  if [ -z "$settings" -o $# -gt 3 ]; then
+    usage
+  fi
+
   if [ -z "$platform" ]; then
     platform='x64'
   fi
@@ -28,7 +52,8 @@ main() {
   fi
 
   local ami='';
-  local ssh_private_key='';
+  local ssh_private_key_path='';
+  local ssh_private_key_contents='';
 
   case "$platform" in
     x64)
@@ -50,8 +75,9 @@ main() {
   fi
 
   if [ "$SSH_PRIVATE_KEY" ]; then
-    ssh_private_key="`cat "$SSH_PRIVATE_KEY"`" \
-      || fatal "Couldn't read private key from '$SSH_PRIVATE_KEY'"
+    ssh_private_key_path="$SSH_PRIVATE_KEY"
+    ssh_private_key_contents="`cat "$ssh_private_key_path"`" \
+      || fatal "Couldn't read private key from '$ssh_private_key_path'"
   fi
 
   if [ -z "$EC2_AVAILABILITY_ZONE" ]; then
@@ -105,28 +131,28 @@ main() {
   echo "Instance name: $external_fqdn"
   echo -n 'Waiting for instance to start... ' >&2
 
-  n='15'
+  n='12'
   local rv='0'
+  local ssh_id="$ssh_private_key_path"
   local ssh_host="ec2-user@$external_fqdn"
-  local ssh_command='ssh -q -o StrictHostKeyChecking=no -o RequestTTY=yes'
 
   while [ "$n" -gt 0 ]; do
 
-    sleep 5 && n=$[n - 1]
+    sleep 10 && n=$[n - 1]
 
-    $ssh_command  "$ssh_host" \
+    ssh_command "$ssh_host" "$ssh_id" \
       'mkdir -p mmva-src/vm-toaster/config/aws-current .ssh' &&
     \
     echo 'done.' >&2 &&
     echo -n 'Establishing connection to instance... ' >&2 &&
     \
-    echo "$settings" | $ssh_command  "$ssh_host" \
+    echo "$settings" | ssh_command  "$ssh_host" "$ssh_id" \
       'cat > mmva-src/vm-toaster/config/aws-current/settings' && \
     \
-    echo "$ssh_private_key" | $ssh_command  "$ssh_host" \
-      'cat >> .ssh/id_rsa' && \
+    echo "$ssh_private_key_contents" \
+      | ssh_command  "$ssh_host" "$ssh_id" 'cat >> .ssh/id_rsa' && \
     \
-    $ssh_command  "$ssh_host" \
+    ssh_command  "$ssh_host" "$ssh_id" \
       "echo 'done.' >&2 &&
          echo 'Connection established successfully.' >&2 &&
          echo -n 'Setting up environment... ' >&2 &&
@@ -149,7 +175,8 @@ main() {
          \
          echo -n 'Extracting MMVA JDK/JRE module... ' >&2 &&
          sudo tar xJf 'mmva-java-$platform-current.tar.xz' &&
-         echo 'done.' >&2 && cd mmva-src &&
+         echo 'done.' >&2 &&
+         cd mmva-src &&
          sudo ln -nsf '$platform' java-current/selected &&
          \
          echo -n 'Installing build-time dependencies... ' >&2 &&
@@ -158,14 +185,13 @@ main() {
          echo 'done.' >&2 &&
          \
          echo -n 'Applying latest MMVA updates... ' >&2 &&
-         (cd vm-toaster && sudo git remote set-url origin "$vm_url" &&
+         (cd vm-toaster &&
+           sudo git remote set-url origin "$vm_url" &&
            sudo git stash -q && sudo git pull -q) &&
          echo 'done.' >&2 &&
          \
          echo 'Starting MMVA build process:' >&2 &&
-         source .profile &&
-         sudo JAVA_HOME="\$JAVA_HOME" \
-           make all PLATFORM='$platform' &&
+         sudo JAVA_HOME="\$JAVA_HOME" make all PLATFORM='$platform' &&
          echo 'MMVA build complete.' >&2 &&
          \
          echo -n 'Building EBS images:' >&2 &&
@@ -178,6 +204,7 @@ main() {
          ./vm-toaster/scripts/upload-iso-images \
            "$UPLOAD_METHOD" "$UPLOAD_USER" \
              "$UPLOAD_HOST" "$UPLOAD_TARGET" "$UPLOAD_OPTIONS" && \
+         \
          echo 'ISO images uploaded successfully.'"
 
     rv="$?"
