Add kujua-transport; fixes to auto-download procedure to tolerate Iriscouch's transient errors.

diff --git a/scripts/retrieve-sources b/scripts/retrieve-sources
--- a/scripts/retrieve-sources
+++ b/scripts/retrieve-sources
@@ -15,6 +15,11 @@ fatal()
   exit 111
 }
 
+warn()
+{
+  echo "Warning: $*" >&2
+}
+
 indent()
 {
   while read line; do echo "  $line"; done
@@ -37,7 +42,14 @@ extract()
         ;;
     esac
 
+    if [ "$?" -ne 0 ]; then
+      warn "Failed to extracting source code from '$archive'"
+      return "$?"
+    fi
+
   done
+
+  return 0
 }
 
 extract_if_necessary()
@@ -138,7 +150,7 @@ main()
 
   echo -n 'Waiting for decompression processes to complete... ' >&2
   wait
-  
+
   touch "$base_dir/status/$manifest_name.retrieved"
   echo 'done.' >&2
 }
diff --git a/source/medic-core-1.3.1/scripts/rearrange-sources b/source/medic-core-1.3.1/scripts/rearrange-sources
--- a/source/medic-core-1.3.1/scripts/rearrange-sources
+++ b/source/medic-core-1.3.1/scripts/rearrange-sources
@@ -90,7 +90,13 @@ apply_patches()
 
 update_garden_maker()
 {
-  (cd garden-maker && ./update.sh)
+  for i in `seq 1 5`; do
+    (cd garden-maker && ./update.sh) && return 0
+    echo 'Failure while updating garden-maker; retrying...' >&2
+  done
+
+  echo 'Too many failures while updating garden-maker; aborting' >&2
+  return "$?"
 }
 
 find_version()
