Directory tree restructuring; self-download functionality. Work in progress.

diff --git a/scripts/retrieve-sources b/scripts/retrieve-sources
--- a/scripts/retrieve-sources
+++ b/scripts/retrieve-sources
@@ -40,6 +40,19 @@ extract()
   done
 }
 
+extract_if_necessary()
+{
+  local url="$1"
+  local name="$2"
+  local origin="$3"
+
+	if ! [ -f "$name.finished" ]; then
+	  (extract "`basename "$url"`" && echo -n "$origin" > "$name.finished") &
+	fi
+
+  return 0
+}
+
 main()
 {
   local manifest_name="$1"
@@ -47,13 +60,30 @@ main()
 
 	if [ $# -lt 2 -o -z "$manifest_name" ]; then
     echo "Usage: $0 manifest_name target_directory" >&2
-		exit 111
+		return 111
   fi
 
 	cd "$target_directory" \
     || fatal "Unable to change to target directory '$target_directory'"
 
+	local manifest_path="../../manifests/$manifest_name"
+
+	local lines="`wc -l "$manifest_path" | cut -d' ' -f1`" \
+    || fatal "Unable to read manifest file 'manifests/$manifest_name'"
+
+	if [ -f "$base_dir/status/$manifest_name.retrieved" ]; then
+    echo "Collection '$manifest_name' is already downloaded; skipping" >&2
+		return 0
+	fi
+
+	local n='0'
+
+	echo >&2
+	echo "Retrieving $lines packages from collection '$manifest_name':" >&2
+
   while read line; do
+
+		local n="$[$n + 1]"
 
     local name="`echo "$line" | cut -d, -f1`"
     name="`basename "$name"`"
@@ -62,11 +92,12 @@ main()
     url="`trim "$url"`"
 
     if [ -f "$name.downloaded" ]; then
-      echo "Skipping already-downloaded package '$name'" >&2
+      echo "[$n/$lines] Skipping already-downloaded package '$name'" >&2
+			extract_if_necessary "$url" "$name" 'curl'
       continue
     fi
 
-    echo "Downloading source code for package '$name'... " >&2
+		echo "[$n/$lines] Downloading source code for package '$name'... " >&2
 
     if [[ "$url" = *.git ]]; then
 
@@ -75,7 +106,7 @@ main()
       [ "${PIPESTATUS[0]}" -eq 0 ] \
         || fatal "Error occurred while cloning repository '$name'"
 
-      echo -n 'git' > "$name.finished"
+      echo -n 'git' > "$name.retrieved"
 
     elif [[ "$url" = "npm "* ]]; then
 
@@ -84,7 +115,7 @@ main()
       [ "${PIPESTATUS[0]}" -eq 0 ] \
         || fatal "Error occurred while retrieving module '$name'"
 
-      echo -n 'npm' > "$name.finished"
+      echo -n 'npm' > "$name.retrieved"
 
     else
 
@@ -99,17 +130,18 @@ main()
         echo -ne "\033[1K\r"
 			fi
 
-      (extract "`basename "$url"`" && echo -n 'curl' > "$name.finished") &
-
+			extract_if_necessary "$url" "$name" 'curl'
     fi
 
     touch "$name.downloaded"
 
   done < "../../manifests/$manifest_name"
 
-  echo -n 'Waiting for decompression processes to complete... '
+  echo -n 'Waiting for decompression processes to complete... ' >&2
   wait
-  echo 'done.'
+	
+	touch "$base_dir/status/$manifest_name.retrieved"
+  echo 'done.' >&2
 }
 
 main "$@"
