Fixes for source code management and package setup.

diff --git a/source/medic-core-1.3.1/scripts/include/builder b/source/medic-core-1.3.1/scripts/include/builder
--- a/source/medic-core-1.3.1/scripts/include/builder
+++ b/source/medic-core-1.3.1/scripts/include/builder
@@ -492,6 +492,11 @@ builder_setup_environment()
   builder_detect_system \
     || fatal 'Unsupported system; please edit Makefile'
 
+	if [ "$bits" -eq 64 ]; then
+	  (cd "$prefix" && rm -rf lib64 && mkdir -p lib && ln -s lib lib64) \
+	    || fatal 'Failed to create symbolic link for 64-bit libraries'
+	fi
+
   if [ "$parallel" ]; then
     export MAKE="$MAKE -j$parallel"
   fi
