Add command-line tools for listing packages, listing/inspecting services, determining service status, etc.

diff --git a/initrd/boot/include/package b/initrd/boot/include/package
--- a/initrd/boot/include/package
+++ b/initrd/boot/include/package
@@ -66,7 +66,7 @@ install_package()
   if [ "$?" -ne 0 ]; then
     return 2
   fi
-
+ 
   mkdir -p "/srv/receipts/$package" &&
     echo -n "$version" > "/srv/receipts/$package/version"
 
@@ -103,15 +103,25 @@ install_package()
 
 remove_package()
 {
-  local package="$1"
+  local package="`basename "$1"`"
 
   if [ -x "/srv/scripts/$package/remove" ]; then
 
+    supervisor_stop "$package"
+    
+    if [ "$?" -ne 0 ]; then
+      warn "Failed to stop services for package '$package'"
+      return 1
+    fi
+    
     "/srv/scripts/$package/remove" \
-      || warn "Removal script for package '$package' failed"
+    
+    if [ "$?" -ne 0 ]; then
+      warn "Removal script for package '$package' failed"
+      return 2
+    fi
 
     rm -rf "/srv/receipts/$package"
-
   fi
 
   sync
@@ -172,6 +182,8 @@ merge_package_environment()
 
 setup_package()
 {
+  local package="`basename "$1"`"
+
   for script in /srv/scripts/$package/setup/*; do
     if [ -x "$script" ]; then
       "$script" \
