Directory reorganization, continued.

diff --git a/platform/scripts/build-ebs-image b/platform/scripts/build-ebs-image
--- a/platform/scripts/build-ebs-image
+++ b/platform/scripts/build-ebs-image
@@ -82,8 +82,6 @@ main()
     fatal "A not-yet-existing block-special device must be specified"
   fi
 
-  local name="MMVA $platform - $description"
-
   local volume_id="`
     ec2-create-volume -s1 \
       -z "$EC2_AVAILABILITY_ZONE" --region "$EC2_REGION" | cut -f2
@@ -91,12 +89,12 @@ main()
 
   wait_for_volume_availability "$volume_id" &&
   \
-  ec2-create-tags "$volume_id" --tag "Name=$name" &>/dev/null \
+  ec2-create-tags "$volume_id" --tag "Name=$description" >/dev/null \
     || fatal "Failure while setting tags on volume'$volume_id'"
 
   ec2-attach-volume "$volume_id" -i "`
     ec2-metadata -i | cut -d: -f2 | sed 's/^ *//'
-  `" -d "$device" &>/dev/null || fatal 'Failed to attach temporary volume'
+  `" -d "$device" >/dev/null || fatal 'Failed to attach temporary volume'
 
   echo "Volume identifier: $volume_id" >&2
   echo -n 'Building EBS system image... ' >&2
@@ -104,7 +102,7 @@ main()
   wait_for_device "$device" \
     || fatal 'Volume did not attach during timeout period'
 
-  sudo mkfs.ext4 "$device" &>/dev/null \
+  sudo mkfs.ext4 "$device" >/dev/null \
     || fatal "Failure while formatting device '$device'"
 
   sudo mkdir -p /mnt/startup &&
@@ -121,7 +119,7 @@ main()
   sudo umount /mnt/loopback /mnt/startup && sudo sync \
     || fatal 'Failure while unmounting volumes'
 
-  ec2-detach-volume --region "$EC2_REGION" "$volume_id" &>/dev/null \
+  ec2-detach-volume --region "$EC2_REGION" "$volume_id" >/dev/null \
     || fatal 'Failure while detaching volume'
 
   echo 'done.' >&2
@@ -134,7 +132,7 @@ main()
 
   wait_for_snapshot_availability "$snapshot_id" &&
   \
-  ec2-create-tags "$snapshot_id" --tag "Name=$name" &>/dev/null \
+  ec2-create-tags "$snapshot_id" --tag "Name=$description" >/dev/null \
     || fatal "Failure while setting tags on snapshot '$snapshot_id'"
 
   echo 'done.' >&2
@@ -151,14 +149,14 @@ main()
   echo 'done.' >&2
   echo "AMI identifier: $ami_id"
 
-  ec2-create-tags "$ami_id" --tag "Name=$name" &>/dev/null \
+  ec2-create-tags "$ami_id" --tag "Name=$name" >/dev/null \
     || fatal "Failure while setting tags on AMI '$ami_id'"
 
   echo -n "Deleting temporary volume '$volume_id'... " >&2
 
   wait_for_volume_availability "$volume_id" &&
   \
-  ec2-delete-volume "$volume_id" &>/dev/null \
+  ec2-delete-volume "$volume_id" >/dev/null \
     || warn "Failure while deleting volume '$volume_id'"
 
   echo 'done.' >&2
diff --git a/platform/scripts/build-source-tarballs b/platform/scripts/build-source-tarballs
--- a/platform/scripts/build-source-tarballs
+++ b/platform/scripts/build-source-tarballs
@@ -21,27 +21,27 @@ main()
   # Clean each platform
   for platform in $platforms; do
 
-    (cd mmva-src && make clean delete PLATFORM="$platform")
+    (cd medic-os && make delete PLATFORM="$platform")
 
     if [ "$?" -ne 0 ]; then
       echo 'failed.' >&2
-      fatal 'Failed to clean MMVA source tree'
+      fatal 'Failed to clean Medic OS source tree'
     fi
   done
 
   # Primary source tree
-  echo -n "Building core MMVA archive... " >&2 &&
+  echo -n "Building core Medic OS archive... " >&2 &&
   \
-  tar -cf - mmva-src \
-    --exclude 'mmva-src/java' \
-    --exclude 'mmva-src/java-current' \
-    --exclude 'mmva-src/vm-toaster/templates/java' \
-    --exclude 'mmva-src/vm-toaster/config/aws-current' \
-      | xz -9ec > "mmva-core-src-$ts.tar.xz"
+  tar -cf - medic-os \
+    --exclude 'medic-os/java' \
+    --exclude 'medic-os/java-current' \
+    --exclude 'medic-os/platform/templates/java' \
+    --exclude 'medic-os/platform/config/aws-current' \
+      | xz -9ec > "medic-os-core-src-$ts.tar.xz"
 
   if [ "$?" -ne 0 ]; then
     echo 'failed.' >&2
-    fatal 'Failed to build core MMVA archive'
+    fatal 'Failed to build core Medic OS archive'
   fi
   
   echo 'done.' >&2
@@ -50,14 +50,14 @@ main()
   for platform in $platforms; do
     echo -n "Building JDK/JRE archive for '$platform'... " >&2 &&
     \
-    (cd 'mmva-src/java-current' && \
+    (cd 'medic-os/java-current' && \
       rm -f selected && ln -sf "$platform" selected) && \
     \
-    tar -cf - 'mmva-src/java' \
-      'mmva-src/java-current/selected' \
-      "mmva-src/java-current/$platform" \
-      "mmva-src/vm-toaster/templates/java/$platform" \
-        | xz -9ec > "mmva-java-$platform-$ts.tar.xz"
+    tar -cf - 'medic-os/java' \
+      'medic-os/java-current/selected' \
+      "medic-os/java-current/$platform" \
+      "medic-os/platform/templates/java/$platform" \
+        | xz -9ec > "medic-os-java-$platform-$ts.tar.xz"
 
     if [ "$?" -ne 0 ]; then
       echo 'failed.' >&2
