Fix typo.

diff --git a/platform/scripts/retrieve-sources b/platform/scripts/retrieve-sources
--- a/platform/scripts/retrieve-sources
+++ b/platform/scripts/retrieve-sources
@@ -180,7 +180,7 @@ main()
   wait
 
   if [ "$?" -ne 0 ]; then
-    echo -n 'failed.' >&2
+    echo 'failed.' >&2
     fatal 'Failed to decompress one or more source code archives'
   fi
 
